ERROR_EMAIL_REGEX = "INPUT_DATA_ERROR"
INPUT_DATA_ERROR = "INPUT_DATA_ERROR"
COURSE_FULL_ERROR = "COURSE_FULL_ERROR"
ACCEPTED = "ACCEPTED"
REJECTED = "REJECTED"
CONFIRMED = "CONFIRMED"
COURSE_CANCELED  = "COURSE_CANCELED"
CANCEL_ACCEPTED = "CANCEL_ACCEPTED"
CANCEL_REJECTED = "CANCEL_REJECTED" 
ALLOCATED = "ALLOCATED"
CANCELLED = "CANCELLED"


